// Path: src/payara-env.ts
// Payara environment configuration utilities

import { execFile, spawn } from 'node:child_process';
import { promisify } from 'node:util';
import { join } from 'node:path';
import { writeFile } from 'node:fs/promises';
import type { Logger } from 'pino';

const execFileAsync = promisify(execFile);

/**
 * Execute a command with stdin input using spawn.
 * Safer than shell interpolation for passing content.
 */
async function execWithStdin(
  command: string,
  args: string[],
  stdin: string
): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn(command, args, {
      stdio: ['pipe', 'ignore', 'pipe'],
    });

    let stderr = '';
    proc.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    proc.on('error', reject);
    proc.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Command failed with code ${code}: ${stderr}`));
      }
    });

    proc.stdin.write(stdin);
    proc.stdin.end();
  });
}

/** Pattern for validating safe usernames (prevents shell injection) */
export const SAFE_USERNAME_PATTERN = /^[a-zA-Z_][a-zA-Z0-9_-]*$/;

/** Pattern for validating safe paths (no shell metacharacters) */
export const SAFE_PATH_PATTERN = /^[a-zA-Z0-9_./-]+$/;

/**
 * Validate that a username is safe for shell commands.
 * @returns true if valid, false otherwise
 */
export function isValidUsername(username: string): boolean {
  return SAFE_USERNAME_PATTERN.test(username);
}

/**
 * Validate that a value is safe for shell interpolation.
 * Throws if the value contains potentially dangerous characters.
 */
export function validateSafeValue(value: string, context: string): void {
  if (!SAFE_PATH_PATTERN.test(value)) {
    throw new Error(`Unsafe ${context}: contains shell metacharacters: ${value}`);
  }
}

/**
 * Options for setenv.conf writer
 */
export interface SetenvWriterOptions {
  payaraHome: string;
  domain: string;
  user?: string;
  logger: Logger;
}

/**
 * Build environment prefix string for command execution.
 *
 * SECURITY: This method ONLY includes non-sensitive env vars (JAVA_HOME).
 * Secrets are written to setenv.conf file which Payara reads on JVM startup.
 * This prevents secrets from appearing in `ps aux`, logs, and error messages.
 *
 * @returns Environment prefix string for shell commands
 */
export function buildEnvPrefix(): string {
  const javaHome = process.env.JAVA_HOME ?? '/usr/lib/jvm/java-21-openjdk-amd64';
  return `JAVA_HOME="${javaHome}" `;
}

/**
 * Sanitize a string for logging by redacting potential secret values.
 * Redacts any quoted string longer than 8 characters.
 *
 * @param str - String to sanitize
 * @returns Sanitized string with secrets redacted
 */
export function sanitizeForLogging(str: string): string {
  return str.replace(/('|")[^'"]{8,}('|")/g, '"[REDACTED]"');
}

/**
 * Write environment variables to domain's setenv.conf.
 * This ensures the Payara JVM receives the env vars on startup.
 *
 * @param environment - Key-value pairs of environment variables
 * @param options - Writer options including paths and user
 */
export async function writeSetenvConf(
  environment: Record<string, string>,
  options: SetenvWriterOptions
): Promise<void> {
  const { payaraHome, domain, user, logger } = options;

  if (Object.keys(environment).length === 0) {
    logger.debug('No environment variables to write');
    return;
  }

  const configDir = join(payaraHome, 'glassfish', 'domains', domain, 'config');
  const setenvPath = join(configDir, 'setenv.conf');

  // Build setenv.conf content
  // Format: export VAR="value"
  const lines: string[] = [
    '# Auto-generated by znvault-plugin-payara',
    '# DO NOT EDIT - this file is overwritten on agent restart',
    '',
  ];

  for (const [key, value] of Object.entries(environment)) {
    // Escape double quotes in value
    const escapedValue = value.replace(/"/g, '\\"');
    lines.push(`export ${key}="${escapedValue}"`);
  }

  const content = lines.join('\n') + '\n';

  logger.info({ path: setenvPath, count: Object.keys(environment).length }, 'Writing setenv.conf');

  const isRoot = process.getuid?.() === 0;

  if (isRoot) {
    // Running as root - direct file write
    await writeFile(setenvPath, content, { mode: 0o640 });

    // Change ownership to payara user
    if (user) {
      // Validate username to prevent injection
      if (!SAFE_USERNAME_PATTERN.test(user)) {
        throw new Error(`Invalid username format: ${user}`);
      }
      try {
        // Use execFile for safe command execution (no shell)
        await execFileAsync('chown', [`${user}:${user}`, setenvPath]);
      } catch (err) {
        logger.warn({ err }, 'Failed to chown setenv.conf');
      }
    }
  } else {
    // Running as non-root - use sudo to write file
    // This requires sudoers rule: user ALL=(root) NOPASSWD: /usr/bin/tee <setenvPath>
    try {
      // Validate path before using in shell commands
      validateSafeValue(setenvPath, 'setenv path');

      // Use spawn with sudo tee for safer command execution
      // Write content via stdin to avoid shell interpretation
      await execWithStdin('sudo', ['tee', setenvPath], content);

      // Set permissions using execFile (no shell)
      await execFileAsync('sudo', ['chmod', '640', setenvPath]);

      // Change ownership to payara user
      if (user) {
        // Validate username to prevent injection
        if (!SAFE_USERNAME_PATTERN.test(user)) {
          throw new Error(`Invalid username format: ${user}`);
        }
        await execFileAsync('sudo', ['chown', `${user}:${user}`, setenvPath]);
      }
    } catch (err) {
      logger.error({ err }, 'Failed to write setenv.conf with sudo');
      throw err;
    }
  }
}

/**
 * Get the path to the setenv.conf file for a domain
 *
 * @param payaraHome - Payara installation directory
 * @param domain - Domain name
 * @returns Full path to setenv.conf
 */
export function getSetenvPath(payaraHome: string, domain: string): string {
  return join(payaraHome, 'glassfish', 'domains', domain, 'config', 'setenv.conf');
}
