// Path: src/payara-env.ts
// Payara environment configuration utilities

import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import { join } from 'node:path';
import { writeFile } from 'node:fs/promises';
import type { Logger } from 'pino';

const execAsync = promisify(exec);

/**
 * Options for setenv.conf writer
 */
export interface SetenvWriterOptions {
  payaraHome: string;
  domain: string;
  user?: string;
  logger: Logger;
}

/**
 * Build environment prefix string for command execution.
 *
 * SECURITY: This method ONLY includes non-sensitive env vars (JAVA_HOME).
 * Secrets are written to setenv.conf file which Payara reads on JVM startup.
 * This prevents secrets from appearing in `ps aux`, logs, and error messages.
 *
 * @returns Environment prefix string for shell commands
 */
export function buildEnvPrefix(): string {
  const javaHome = process.env.JAVA_HOME ?? '/usr/lib/jvm/java-21-openjdk-amd64';
  return `JAVA_HOME="${javaHome}" `;
}

/**
 * Sanitize a string for logging by redacting potential secret values.
 * Redacts any quoted string longer than 8 characters.
 *
 * @param str - String to sanitize
 * @returns Sanitized string with secrets redacted
 */
export function sanitizeForLogging(str: string): string {
  return str.replace(/('|")[^'"]{8,}('|")/g, '"[REDACTED]"');
}

/**
 * Write environment variables to domain's setenv.conf.
 * This ensures the Payara JVM receives the env vars on startup.
 *
 * @param environment - Key-value pairs of environment variables
 * @param options - Writer options including paths and user
 */
export async function writeSetenvConf(
  environment: Record<string, string>,
  options: SetenvWriterOptions
): Promise<void> {
  const { payaraHome, domain, user, logger } = options;

  if (Object.keys(environment).length === 0) {
    logger.debug('No environment variables to write');
    return;
  }

  const configDir = join(payaraHome, 'glassfish', 'domains', domain, 'config');
  const setenvPath = join(configDir, 'setenv.conf');

  // Build setenv.conf content
  // Format: export VAR="value"
  const lines: string[] = [
    '# Auto-generated by znvault-plugin-payara',
    '# DO NOT EDIT - this file is overwritten on agent restart',
    '',
  ];

  for (const [key, value] of Object.entries(environment)) {
    // Escape double quotes in value
    const escapedValue = value.replace(/"/g, '\\"');
    lines.push(`export ${key}="${escapedValue}"`);
  }

  const content = lines.join('\n') + '\n';

  logger.info({ path: setenvPath, count: Object.keys(environment).length }, 'Writing setenv.conf');

  // Write file (needs to be readable by payara user)
  await writeFile(setenvPath, content, { mode: 0o640 });

  // Change ownership to payara user
  if (process.getuid?.() === 0 && user) {
    try {
      await execAsync(`chown ${user}:${user} "${setenvPath}"`);
    } catch (err) {
      logger.warn({ err }, 'Failed to chown setenv.conf');
    }
  }
}

/**
 * Get the path to the setenv.conf file for a domain
 *
 * @param payaraHome - Payara installation directory
 * @param domain - Domain name
 * @returns Full path to setenv.conf
 */
export function getSetenvPath(payaraHome: string, domain: string): string {
  return join(payaraHome, 'glassfish', 'domains', domain, 'config', 'setenv.conf');
}
